[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$FkKoVcqZM8Y4B8B4z/n/fw$gWoHdlNVfMdH6q0NfosRqsKKgWZQhPi9O.Hq7Bvqrv1QaS2JoxNciscMCwHRnnUx9z2HkwFDJE82dL5QBhpBrA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dev_mode = reload,qweb,xml
log_level = info

